### ISSUE TITLE
sugestão de challenge

### ISSUE THREAD

**Issue by miqueiasousa** [michelbernardods/programming-challenges#1]
-> EDABIT https://edabit.com
gosto muito desse site por ter challenges menores, muito bom para iniciante

**Comment by michelbernardods** [comment]
> -> EDABIT https://edabit.com
> gosto muito desse site por ter challenges menores, muito bom para iniciante



> -> EDABIT https://edabit.com
> gosto muito desse site por ter challenges menores, muito bom para iniciante

Olá, já se encontra na lista.
